-- lua/custom/plugins/java-kotlin.lua
--
-- Java + Kotlin IDE support for this repo is handled by a SINGLE language
-- server: JetBrains' kotlin-lsp (IntelliJ-based, Mason package 'kotlin-lsp',
-- binary `intellij-server`). Because it is the IntelliJ engine, it indexes and
-- serves BOTH .kt and .java files in the same Gradle workspace, so cross-
-- language navigation/identification (Kotlin → Java and back) works from one
-- index — exactly what you want in this polyglot 60+ module repo.
--
-- It is configured entirely in init.lua:
--   • `servers.kotlin_lsp` in the lspconfig setup
--   • the `vim.lsp.config('kotlin_lsp', …)` override that pins the cache dir and
--     extends `filetypes` to include 'java'
--
-- We deliberately do NOT use nvim-jdtls / Eclipse JDT anymore. Running jdtls
-- alongside kotlin_lsp meant two servers indexing the same tree, and jdtls's
-- Eclipse Gradle import polluted every module with .project/.classpath/
-- .settings/ and copied .kt sources into bin/ output folders. One IntelliJ-grade
-- server avoids all of that.
--
-- Nothing to install here — Mason installs kotlin-lsp via mason-tool-installer
-- in init.lua, and lspconfig handles the rest. This file intentionally declares
-- no plugins.
return {}
